apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rendszam-frontend
  template:
    metadata:
      labels:
        app: rendszam-frontend
    spec:
      containers:
        - name: frontend
          image: rendszam-frontend:latest
          ports:
            - containerPort: 80
